apiVersion: v1
kind: Secret
metadata:
  name: havyn-api-secrets
  namespace: havyn-villa
type: Opaque
stringData:
  POSTGRES_USER: replace-me
  POSTGRES_PASSWORD: replace-me
  JWT_ACCESS_SECRET: replace-me-with-high-entropy-secret
  JWT_REFRESH_SECRET: replace-me-with-a-different-high-entropy-secret
  PAYSTACK_SECRET_KEY: replace-me
  FLUTTERWAVE_SECRET_KEY: replace-me
  FLUTTERWAVE_WEBHOOK_HASH: replace-me
  RAYPROP_API_KEY: replace-me
  MINIO_ROOT_USER: replace-me
  MINIO_ROOT_PASSWORD: replace-me
  CLOUDINARY_API_KEY: replace-me
  CLOUDINARY_API_SECRET: replace-me
  GOOGLE_CLIENT_SECRET: replace-me
  OPENAI_API_KEY: replace-me
  MAIL_API_KEY: replace-me
  HAVYN_BOOTSTRAP_ADMIN_EMAIL: replace-me
  HAVYN_BOOTSTRAP_ADMIN_PASSWORD: replace-me
