apiVersion: v1
kind: Service
metadata:
  name: havyn-api
  namespace: havyn-villa
spec:
  type: NodePort
  selector:
    app: havyn-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
